In [32]:
import pandas as pd

file_path1 = "Schreibmaschinen.csv"
file_path2 = "Liste_AK Kommunikation.csv"

In [33]:
# Erstmal mit Latin1 (ISO-8859-1), oft Standard bei Windows/Excel
schreibmaschienen_df = pd.read_csv(file_path1, encoding="cp1252", sep=";",header=None, skiprows=1)
kommunikation_df = pd.read_csv(file_path2, encoding="cp1252", sep=";",header=None, skiprows=1)

In [34]:
# Überblick
print(schreibmaschienen_df.shape)
print(schreibmaschienen_df.columns)
schreibmaschienen_df.head()

(125, 84)
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
      dtype='int64')

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,NaN,NaN,NaN,NaN,1/2024/0501 0,Mercedes BŸromaschinenwerke AG\nunbekannt,NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 7.1.KTD EG S 53.B 02,NaN,NaN,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1930er Jahre",NaN
1,NaN,NaN,NaN,NaN,1/2024/0501 0,Mercedes BŸromaschinenwerke AG\nunbekannt,NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 7.1.KTD EG S 53.B 02,NaN,NaN,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1930er Jahre",NaN
2,NaN,NaN,NaN,NaN,1/2024/0501 0,Mercedes BŸromaschinenwerke AG\nunbekannt,NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 7.1.KTD EG S 53.B 02,NaN,NaN,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1930er Jahre",NaN
3,NaN,NaN,NaN,NaN,1/2024/0501 0,Mercedes BŸromaschinenwerke AG\nunbekannt,NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 7.1.KTD EG S 53.B 02,NaN,NaN,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1930er Jahre",NaN
4,NaN,NaN,NaN,NaN,1/2024/0501 0,Mercedes BŸromaschinenwerke AG\nunbekannt,NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 7.1.KTD EG S 53.B 02,NaN,NaN,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1930er Jahre",NaN

In [35]:
# Überblick
print(kommunikation_df.shape)
print(kommunikation_df.columns)
kommunikation_df.head()

(1153, 84)
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
      dtype='int64')

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,NaN,NaN,NaN,NaN,1/2024/0061 0,RFT Fernmeldewerk (VEB),NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 6.KTD SR 05.F 15.B 07,NaN,Der Tischapparat W 38 (WŠhlapparat 38) wurde i...,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1950er Jahre",NaN
1,NaN,NaN,NaN,NaN,1/2024/0061 0,RFT Fernmeldewerk (VEB),NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 6.KTD SR 05.F 15.B 07,NaN,Der Tischapparat W 38 (WŠhlapparat 38) wurde i...,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1950er Jahre",NaN
2,NaN,NaN,NaN,NaN,1/2024/0061 0,RFT Fernmeldewerk (VEB),NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 6.KTD SR 05.F 15.B 07,NaN,Der Tischapparat W 38 (WŠhlapparat 38) wurde i...,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1950er Jahre",NaN
3,NaN,NaN,NaN,NaN,1/2024/0061 0,RFT Fernmeldewerk (VEB),NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 6.KTD SR 05.F 15.B 07,NaN,Der Tischapparat W 38 (WŠhlapparat 38) wurde i...,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1950er Jahre",NaN
4,NaN,NaN,NaN,NaN,1/2024/0061 0,RFT Fernmeldewerk (VEB),NaN,NaN,NaN,NaN,...,NaN,NaN,RZ 6.KTD SR 05.F 15.B 07,NaN,Der Tischapparat W 38 (WŠhlapparat 38) wurde i...,NaN,NaN,\\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...,"Herstellungsjahr, 1950er Jahre",NaN

In [36]:
# Nur die ersten 300 Zeilen behalten
kommunikation_df300 = kommunikation_df.head(300)
kommunikation_df300.info

<bound method DataFrame.info of      0   1   2   3              4   \
0   NaN NaN NaN NaN  1/2024/0061 0
1   NaN NaN NaN NaN  1/2024/0061 0
2   NaN NaN NaN NaN  1/2024/0061 0
3   NaN NaN NaN NaN  1/2024/0061 0
4   NaN NaN NaN NaN  1/2024/0061 0
..   ..  ..  ..  ..            ...
295 NaN NaN NaN NaN  1/2024/0348 0
296 NaN NaN NaN NaN  1/2024/0348 0
297 NaN NaN NaN NaN  1/2024/0348 0
298 NaN NaN NaN NaN  1/2024/0348 0
299 NaN NaN NaN NaN  1/2024/0349 0

                                                    5   6   7   8   9   ...  \
0                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
1                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
2                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
3                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
4                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
..                                                 ...  ..  ..  ..  ..  ...
295  Polygram GmbH\nEntertainment Distribution Comp... NaN NaN NaN NaN  ...
296  Polygram GmbH\nEntertainment Distribution Comp... NaN NaN NaN NaN  ...
297  Polygram GmbH\nEntertainment Distribution Comp... NaN NaN NaN NaN  ...
298  Polygram GmbH\nEntertainment Distribution Comp... NaN NaN NaN NaN  ...
299  Koch Digitaldisc GmbH\nEntertainment Distribut... NaN NaN NaN NaN  ...

     74  75                             76  77  \
0   NaN NaN       RZ 6.KTD SR 05.F 15.B 07 NaN
1   NaN NaN       RZ 6.KTD SR 05.F 15.B 07 NaN
2   NaN NaN       RZ 6.KTD SR 05.F 15.B 07 NaN
3   NaN NaN       RZ 6.KTD SR 05.F 15.B 07 NaN
4   NaN NaN       RZ 6.KTD SR 05.F 15.B 07 NaN
..   ..  ..                            ...  ..
295 NaN NaN       RZ 6.KTD.SR 04.F 49.B 02 NaN
296 NaN NaN       RZ 6.KTD.SR 04.F 49.B 02 NaN
297 NaN NaN       RZ 6.KTD.SR 04.F 49.B 02 NaN
298 NaN NaN       RZ 6.KTD.SR 04.F 49.B 02 NaN
299 NaN NaN  RZ 3. Exponat-Eingangsbereich NaN

                                                    78  79   80  \
0    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
1    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
2    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
3    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
4    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
..                                                 ...  ..  ...
295                                                NaN NaN  NaN
296                                                NaN NaN  NaN
297                                                NaN NaN  NaN
298                                                NaN NaN  NaN
299                                                NaN NaN  NaN

                                                    81  \
0    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
1    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
2    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
3    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
4    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
..                                                 ...
295  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
296  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
297  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
298  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
299  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...

                                 82  83
0    Herstellungsjahr, 1950er Jahre NaN
1    Herstellungsjahr, 1950er Jahre NaN
2    Herstellungsjahr, 1950er Jahre NaN
3    Herstellungsjahr, 1950er Jahre NaN
4    Herstellungsjahr, 1950er Jahre NaN
..                              ...  ..
295                         um 1980 NaN
296                         um 1980 NaN
297                         um 1980 NaN
298                         um 1980 NaN
299                         um 1990 NaN

[300 rows x 84 columns]>

In [37]:

# Untereinander anhängen
df_combined = pd.concat([kommunikation_df300,schreibmaschienen_df], ignore_index=True)

print(df_combined)

     0   1   2   3              4   \
0   NaN NaN NaN NaN  1/2024/0061 0
1   NaN NaN NaN NaN  1/2024/0061 0
2   NaN NaN NaN NaN  1/2024/0061 0
3   NaN NaN NaN NaN  1/2024/0061 0
4   NaN NaN NaN NaN  1/2024/0061 0
..   ..  ..  ..  ..            ...
420 NaN NaN NaN NaN  1/2025/0767 0
421 NaN NaN NaN NaN  1/2025/0767 0
422 NaN NaN NaN NaN  1/2025/0767 0
423 NaN NaN NaN NaN  1/2025/0767 0
424 NaN NaN NaN NaN  1/2025/0767 0

                                                    5   6   7   8   9   ...  \
0                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
1                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
2                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
3                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
4                              RFT Fernmeldewerk (VEB) NaN NaN NaN NaN  ...
..                                                 ...  ..  ..  ..  ..  ...
420  VEB Schreibmaschinenwerk Dresden im VEB Kombin... NaN NaN NaN NaN  ...
421  VEB Schreibmaschinenwerk Dresden im VEB Kombin... NaN NaN NaN NaN  ...
422  VEB Schreibmaschinenwerk Dresden im VEB Kombin... NaN NaN NaN NaN  ...
423  VEB Schreibmaschinenwerk Dresden im VEB Kombin... NaN NaN NaN NaN  ...
424  VEB Schreibmaschinenwerk Dresden im VEB Kombin... NaN NaN NaN NaN  ...

     74  75                        76  77  \
0   NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
1   NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
2   NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
3   NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
4   NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
..   ..  ..                       ...  ..
420 NaN NaN  RZ 6.KTD SR 16.F 39.B 05 NaN
421 NaN NaN  RZ 6.KTD SR 16.F 39.B 05 NaN
422 NaN NaN  RZ 6.KTD SR 16.F 39.B 05 NaN
423 NaN NaN  RZ 6.KTD SR 16.F 39.B 05 NaN
424 NaN NaN  RZ 6.KTD SR 16.F 39.B 05 NaN

                                                    78  79   80  \
0    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
1    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
2    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
3    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
4    Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
..                                                 ...  ..  ...
420                                                NaN NaN  NaN
421                                                NaN NaN  NaN
422                                                NaN NaN  NaN
423                                                NaN NaN  NaN
424                                                NaN NaN  NaN

                                                    81  \
0    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
1    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
2    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
3    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
4    \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
..                                                 ...
420  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
421  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
422  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
423  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
424  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...

                                 82  83
0    Herstellungsjahr, 1950er Jahre NaN
1    Herstellungsjahr, 1950er Jahre NaN
2    Herstellungsjahr, 1950er Jahre NaN
3    Herstellungsjahr, 1950er Jahre NaN
4    Herstellungsjahr, 1950er Jahre NaN
..                              ...  ..
420                     1965 - 1976 NaN
421                     1965 - 1976 NaN
422                     1965 - 1976 NaN
423                     1965 - 1976 NaN
424                     1965 - 1976 NaN

[425 rows x 84 columns]

In [47]:
# 2. Werte in Spalte 4 bereinigen (/ -> -)
df_combined.iloc[:, 4] = df_combined.iloc[:, 4].astype(str).str.replace("/", "-", regex=False)

# 3. Nach Spalte 4 eindeutige Zeilen behalten
df_unique = df_combined.drop_duplicates(subset=df_combined.columns[4]).reset_index(drop=True)

print(df_unique.shape)
print(df_unique.head())

(101, 84)
   0   1   2   3              4                               5   6   7   8   \
0 NaN NaN NaN NaN  1-2024-0061 0         RFT Fernmeldewerk (VEB) NaN NaN NaN
1 NaN NaN NaN NaN  1-2024-0062 0         RFT Fernmeldewerk (VEB) NaN NaN NaN
2 NaN NaN NaN NaN  1-2024-0063 0  Siemens & Halske AG\nunbekannt NaN NaN NaN
3 NaN NaN NaN NaN  1-2024-0064 0  Siemens & Halske AG\nunbekannt NaN NaN NaN
4 NaN NaN NaN NaN  1-2024-0065 0  Siemens & Halske AG\nunbekannt NaN NaN NaN

   9   ...  74  75                        76  77  \
0 NaN  ... NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
1 NaN  ... NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
2 NaN  ... NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
3 NaN  ... NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN
4 NaN  ... NaN NaN  RZ 6.KTD SR 05.F 15.B 07 NaN

                                                  78  79   80  \
0  Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
1  Der Tischapparat W 38 (WŠhlapparat 38) wurde i... NaN  NaN
2  Das analoge Wandtelefon W 28 (WŠhlapparat 28) ... NaN  NaN
3  Prinzip der Reihenanlage: \nDie Reihenanlage (... NaN  NaN
4                                                NaN NaN  NaN

                                                  81  \
0  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
1  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
2  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
3  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...
4  \\dtmbgw2\museumplus\Objektbilder\verknŸpft\20...

                               82  83
0  Herstellungsjahr, 1950er Jahre NaN
1  Herstellungsjahr, 1950er Jahre NaN
2                    1930er Jahre NaN
3                    1960er Jahre NaN
4                    1960er Jahre NaN

[5 rows x 84 columns]

In [48]:
df_unique.to_csv("fertig.csv", index=False, encoding="utf-8")